INSERT INTO treatments (name, price, drug, type) VALUES ("Ampiclox 250mg susp", 4000, "Penicillin- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ampicloxacilline caps 500mg", 200, "Penicillin- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Susp Amoxicillln/Clavuline 156 m", 14000, "Penicillin- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Susp Amoxicillin/Clavuline 228m", 15000, "Penicillin- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Amoxiclavulin 625mg- Fleming", 980, "Penicillin- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Amoxiclavulin- Koact", 980, "Penicillin- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Flucloxacillin/Flucamox tabs", 980, "Penicillin- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Amoxicillin Caps 250mg", 150, "Penicillin- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Amoxicillin Caps 500mg", 250, "Penicillin- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Cephalexin 250mg caps", 250, "Cephalosporin- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Cephalexine susp125mg/5ml", 6000, "Cephalosporin- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ciprofloxacin Tabs 500mg", 200, "Fluoroquinolones", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Nalidixic Acid Tabs", 250, "Fluoroquinolones", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Norfloxacin + Tinidazole tabs", 250, "Fluoroquinolones", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Norfloxacin + Tinidazole tabs", 250, "Fluoroquinolones", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Erythromycin tabs", 150, "Macrolide- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Erythromycin suspension", 3000, "Macrolide- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Azithromycin 500mg 6s", 1000, "Macrolide- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Clarythromycin susp", 15000, "Macrolide- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Clarythromycin 500mg tbs", 1800, "Macrolide- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Azithromycin syrup", 5000, "Macrolide- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Co-trimoxazole syr", 2000, "Sulfonamides- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Co-trimoxazole tabs", 80, "Sulfonamides- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Nitrofurantoin500mg tbs", 100, "Sulfonamides- oral", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Doxicycline100mg", 150, "Tetracycline", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ampicillin SOOmg inj", 2000, "Penicillins", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ampicillin + Cloxacillininj500mg", 3000, "Penicillins", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Benzathine penicillininj", 2000, "Penicillins", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("BenzylpenicillinSmu", 2000, "Penicillins", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ceftriaxone 250mginj", 3000, "Cephalosporin", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ceftriaxone SOOmg inj", 3500, "Cephalosporin", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ceftriaxone lg inj", 4000, "Cephalosporin", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Gentamycininj 80mg", 2000, "Aminoglycosides", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Clindamycin Gel", 10000, "Aminoglycosides", "ANTIBIOTICS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Artemether/lumefantrine tabs- ALU 6s", 2000, "Artemisinin", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Artemether/lumefantrine tabs- ALU 12s", 2500, "Artemisinin", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Artemether/lumefantrine tabs- ALU 18s", 2700, "Artemisinin", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Artemether/lumefantrine tabs- ALU 24s", 3000, "Artemisinin", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Dihydroartemisinin/piperaquine tabs- duocortexin", 14000, "Artemisinin", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Dihydroartemisinin/piperaquine tabs- O-Artep", 14000, "Artemisinin", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Artesunate 30mginj", 5500, "Artemisinin", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Artesunate 60mg inj", 9000, "Artemisinin", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Artesunate120mg inj", 12000, "Artemisinin", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Artesunate susp", 8500, "Artemisinin", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Artemether for ln]. 80mg", 4000, "Artemisinin", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("ALU syrup/LATERM Susp 60mls", 7000, "Artemisinin", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("ALU syrup/CO-artesiane Susp 120mls", 14000, "Artemisinin", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Quinine syrp", 3000, "Quinine", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Quinine 600mginj10 amp", 2000, "Quinine", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Quinine tabs 300mg", 300, "Quinine", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Sulphadoxine/pyrimethamine", 2000, "Others", "ANTIMALARIAL");
INSERT INTO treatments (name, price, drug, type) VALUES ("Acyclovir 400mg tabs", 550, "Antiviral", "Antiviral");
INSERT INTO treatments (name, price, drug, type) VALUES ("Acyclovir cream", 4000, "Antiviral", "Antiviral");
INSERT INTO treatments (name, price, drug, type) VALUES ("ltraconazole l00mg", 800, "Azoles", "Antifungal");
INSERT INTO treatments (name, price, drug, type) VALUES ("Fluconazole 150mg tabs", 1000, "Azoles", "Antifungal");
INSERT INTO treatments (name, price, drug, type) VALUES ("Terbinafine 250mg tabs", 200, "Allylamine", "Antifungal");
INSERT INTO treatments (name, price, drug, type) VALUES ("Terbinafine Topical Cream", 6000, "Allylamine", "Antifungal");
INSERT INTO treatments (name, price, drug, type) VALUES ("Clotrimazole v. pessaries", 4000, "Others", "Antifungal");
INSERT INTO treatments (name, price, drug, type) VALUES ("Clotrimazole v. cream+ applicator- candid v.gel", 4000, "Others", "Antifungal");
INSERT INTO treatments (name, price, drug, type) VALUES ("Miconazole V Pessaries", 12000, "Others", "Antifungal");
INSERT INTO treatments (name, price, drug, type) VALUES ("Griseofluvin Tabs 500mg", 300, "Others", "Antifungal");
INSERT INTO treatments (name, price, drug, type) VALUES ("Benzoyl Peroxide Cream/PERSOL", 5000, "Others", "Antifungal");
INSERT INTO treatments (name, price, drug, type) VALUES ("Nitazoxanide 500mg", 1700, "Antiparasitic", "Antiparasitic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Nitazoxanide susp", 10500, "Antiparasitic", "Antiparasitic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Albendazole tabs 400mg", 1500, "Antiparasitic", "Antiparasitic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Albendazole Susp 400mg", 1500, "Antiparasitic", "Antiparasitic");
INSERT INTO treatments (name, price, drug, type) VALUES ("MebendazolelOOmg tab", 150, "Antiparasitic", "Antiparasitic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Mebendazole susp", 1800, "Antiparasitic", "Antiparasitic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Levamisole tabs", 500, "Antiparasitic", "Antiparasitic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Praziquantel tabs 600mg", 800, "Antiparasitic", "Antiparasitic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Metronidazole 200mg/Sml susp", 2000, "Antiparasitic", "Antiparasitic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Metronidazole 200mg tabs", 70, "Antiparasitic", "Antiparasitic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Secnidazole B/2 tab", 4000, "Antiparasitic", "Antiparasitic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Tinidazole 500mgtab", 600, "Antiparasitic", "Antiparasitic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Candiderm cream", 5000, "Topical", "Topical");
INSERT INTO treatments (name, price, drug, type) VALUES (" Ketoconazole cream", 3000, "Topical", "Topical");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ketoconazole shampoo", 18000, "Topical", "Topical");
INSERT INTO treatments (name, price, drug, type) VALUES ("Mupirocin ointment - supirocin", 15000, "Topical", "Topical");
INSERT INTO treatments (name, price, drug, type) VALUES ("Salicylic acid", 25000, "Oiprosalic", "Topical");
INSERT INTO treatments (name, price, drug, type) VALUES ("Hydrocortisone cream", 2500, "Oiprosalic", "Topical");
INSERT INTO treatments (name, price, drug, type) VALUES ("Scabomalotion", 6000, "Scabies", "Scabies");
INSERT INTO treatments (name, price, drug, type) VALUES ("Scaboma Cream", 9000, "Scabies", "Scabies");
INSERT INTO treatments (name, price, drug, type) VALUES ("Aceclofenac l00mg tab", 200, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Diclofenac potassium 50mg - Fla mar MX", 600, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Volin gel", 5000, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Meloxicam 7 .Smg tabs", 350, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Meloxicam lSmg tabs", 500, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Mefenamic acid250mg/500mg", 200, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("lbprofen 200mg", 105, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("lbumex syrup", 3000, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Didofenac sodium 50mg", 150, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Didofenac lnj", 2000, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ketoprofen Tabs", 600, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ketoprofen Gel 50mg", 15000, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("lbprofen200mg + Paracetamol", 400, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Indomethacine Caps 25mg", 150, "Analgesics", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Paracetamol 500mg tabs", 150, "Acetaminophen", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Paracetamol syrup", 2000, "Acetaminophen", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("TriganD -Dycoclamine + Paracetamol", 1000, "Acetaminophen", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Tramadol 50mg tabs", 200, "Opioids", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Tramadol injl00mg", 2000, "Opioids", "Analgesics");
INSERT INTO treatments (name, price, drug, type) VALUES ("Aerocort inhaler/lbicar-s - Salbutm +bedometasone", 16000, "Inhalers", "Antiasthmatic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Salbutamolinhaler", 7500, "Inhalers", "Antiasthmatic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Budesonide inhaler", 18000, "Inhalers", "Antiasthmatic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Formetorol+Budesonide inhaler", 25000, "Inhalers", "Antiasthmatic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Salbutamoltabs", 70, "Inhalers", "Antiasthmatic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Aminophylline injl00mg", 2500, "Xanthine", "Antiasthmatic");
INSERT INTO treatments (name, price, drug, type) VALUES ("AminophyllineTabs 100mg", 150, "Xanthine", "Antiasthmatic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Montelukast5mg", 1000, "LR Antagonist", "Antiasthmatic");
INSERT INTO treatments (name, price, drug, type) VALUES ("montelukastl0mg", 1100, "LR Antagonist", "Antiasthmatic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Arnlodipine 5mg tabs", 200, "Ca+ Chanelblocker", "Cardiovascular");
INSERT INTO treatments (name, price, drug, type) VALUES ("Amlodipinel0mg tabs", 250, "Ca+ Chanelblocker", "Cardiovascular");
INSERT INTO treatments (name, price, drug, type) VALUES ("Nifedipine 20mg tabs", 150, "Ca+ Chanelblocker", "Cardiovascular");
INSERT INTO treatments (name, price, drug, type) VALUES ("Carvedilol 6.Smg", 600, "Beta-blocker", "Cardiovascular");
INSERT INTO treatments (name, price, drug, type) VALUES ("Carvedilol12.5mg", 1000, "Beta-blocker", "Cardiovascular");
INSERT INTO treatments (name, price, drug, type) VALUES ("Atenolol 50mg", 150, "Beta-blocker", "Cardiovascular");
INSERT INTO treatments (name, price, drug, type) VALUES (" Lisinoprill0mg", 450, "ACE Inhibitor", "Cardiovascular");
INSERT INTO treatments (name, price, drug, type) VALUES (" Lisinopril 5mg", 300, "ACE Inhibitor", "Cardiovascular");
INSERT INTO treatments (name, price, drug, type) VALUES (" Ramipril2.5mg", 500, "ACE Inhibitor", "Cardiovascular");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ramipril5mg", 800, "ACE Inhibitor", "Cardiovascular");
INSERT INTO treatments (name, price, drug, type) VALUES (" Captopril 25mg", 200, "ACE Inhibitor", "Cardiovascular");
INSERT INTO treatments (name, price, drug, type) VALUES ("losartan 50mg tabs", 500, "Arbs", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("Candesartan 8mg tabs", 200, "Arbs", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("lrbesartan", 500, "Arbs", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("Telmisartan 20mg", 1000, "Arbs", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("Telmisartan40mg", 14000, "Arbs", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("Telmisartan 80mg", 3200, "Arbs", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES (" Telmisartan+ Hct 40mg/12.5mgs", 2000, "Arbs", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("Telmisartan+ Hct 80mg/12.5mgs", 2000, "Arbs", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("Losartan/hydrochlorothiazides 50/12.5mg tabs", 1200, "Arbs", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("lasix 40mg tabs", 150, "Loop diuretics", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("Bendroflumethiazide 5mg", 200, "Thiazides", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("Hydralazine 2Smg tabs", 200, "Vasodilators", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("Hydralazine inj5mg", 15000, "Vasodilators", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("Spironolactone25mg tabs", 1200, "Aldosterone antagonist", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("lsosorbide dinitrate10mg tabs", 100, "Nitrates", "Arbs");
INSERT INTO treatments (name, price, drug, type) VALUES ("Atovastatinl0rng", 400, "Statin", "Statin");
INSERT INTO treatments (name, price, drug, type) VALUES (" Atovastatin20mg", 500, "Statin", "Statin");
INSERT INTO treatments (name, price, drug, type) VALUES ("Methyldopa tabs 250mg", 300, "Others", "Statin");
INSERT INTO treatments (name, price, drug, type) VALUES ("Acetylsalicylic acid75mg tabs", 150, "Others", "Statin");
INSERT INTO treatments (name, price, drug, type) VALUES ("Clopidogrel75mg tabs", 500, "Others", "Statin");
INSERT INTO treatments (name, price, drug, type) VALUES ("Adrenaline injection", 2000, "Others", "Statin");
INSERT INTO treatments (name, price, drug, type) VALUES ("Metfomin tbs500mg", 150, "Biguanides", "Antidiabetic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Chlorpropamide 250mgtabs", 200, "Sulfonylureas", "Antidiabetic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Glibenclamide Smg tabs", 150, "Sulfonylureas", "Antidiabetic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Grimepride + Metformin tabs - Gerner 1", 1000, "Sulfonylureas", "Antidiabetic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Grimepride + Metformin tabs - Gerner 2", 1500, "Sulfonylureas", "Antidiabetic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Glibenclamide + Metformin 5/500mg", 1000, "Sulfonylureas", "Antidiabetic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Insulin lente", 23000, "Insulin", "Antidiabetic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Insulinsoluble", 23000, "Insulin", "Antidiabetic");
INSERT INTO treatments (name, price, drug, type) VALUES ("Mixtard", 23000, "Insulin", "Antidiabetic");
INSERT INTO treatments (name, price, drug, type) VALUES (" AllupurinollOOmg tab", 400, "Rheumatoid", "Rheumatoid");
INSERT INTO treatments (name, price, drug, type) VALUES ("Allupurinol300mg tab", 500, "Rheumatoid", "Rheumatoid");
INSERT INTO treatments (name, price, drug, type) VALUES ("Glucosamine/Chondroitintabs", 3000, "Others", "Rheumatoid");
INSERT INTO treatments (name, price, drug, type) VALUES ("Esomeprazo1e 20mgcap", 500, "PP inhibitors", "Proton pump inhibitors");
INSERT INTO treatments (name, price, drug, type) VALUES ("Esomeprazo1e 40mgcap", 1000, "PP inhibitors", "Proton pump inhibitors");
INSERT INTO treatments (name, price, drug, type) VALUES ("Lansoprazole caps 30mg", 400, "PP inhibitors", "Proton pump inhibitors");
INSERT INTO treatments (name, price, drug, type) VALUES ("Pantoprazole Tabs 40mg", 1000, "PP inhibitors", "Proton pump inhibitors");
INSERT INTO treatments (name, price, drug, type) VALUES ("Pantoprazole 40mg lnj.", 25000, "PP inhibitors", "Proton pump inhibitors");
INSERT INTO treatments (name, price, drug, type) VALUES ("Omeprazole 20mg", 150, "PP inhibitors", "Proton pump inhibitors");
INSERT INTO treatments (name, price, drug, type) VALUES ("Rabeprazole tabs 20mg", 1500, "PP inhibitors", "Proton pump inhibitors");
INSERT INTO treatments (name, price, drug, type) VALUES ("Rabeprazolelnj", 50000, "PP inhibitors", "Proton pump inhibitors");
INSERT INTO treatments (name, price, drug, type) VALUES ("Heligo kit", 45000, "H.pylori kit", "H.pylori kit");
INSERT INTO treatments (name, price, drug, type) VALUES (" Relcer gel - Antacidmixt180mls", 8000, "Antiacid", "Antiacid");
INSERT INTO treatments (name, price, drug, type) VALUES ("Relcer gel {Antacidmixtl00mls", 4000, "Antiacid", "Antiacid");
INSERT INTO treatments (name, price, drug, type) VALUES ("Lucid susp", 15000, "Antiacid", "Antiacid");
INSERT INTO treatments (name, price, drug, type) VALUES ("Alugel susp", 3000, "Antiacid", "Antiacid");
INSERT INTO treatments (name, price, drug, type) VALUES ("Altaphamsusp", 3000, "Antiacid", "Antiacid");
INSERT INTO treatments (name, price, drug, type) VALUES ("Metodopropamide tbs l0mg", 350, "Antiemetics", "Gut Motility");
INSERT INTO treatments (name, price, drug, type) VALUES ("Metoclopramidel0mg inj", 2000, "Antiemetics", "Gut Motility");
INSERT INTO treatments (name, price, drug, type) VALUES ("Domperidonel0mg tabs", 250, "Antiemetics", "Gut Motility");
INSERT INTO treatments (name, price, drug, type) VALUES ("Domperidone susp", 5000, "Antiemetics", "Gut Motility");
INSERT INTO treatments (name, price, drug, type) VALUES ("Bisarcodyl 5mg tabs", 200, "Laxatives", "Gut Motility");
INSERT INTO treatments (name, price, drug, type) VALUES ("Lactulose syrpl00ml", 8000, "Laxatives", "Gut Motility");
INSERT INTO treatments (name, price, drug, type) VALUES ("loperamide2mg tabs", 150, "Antidiarrhea", "Gut Motility");
INSERT INTO treatments (name, price, drug, type) VALUES ("Buscopan10Mg lnj", 2000, "Antispasmodic", "Gut Motility");
INSERT INTO treatments (name, price, drug, type) VALUES (" Buscopan Tabs 10mg", 600, "Antispasmodic", "Gut Motility");
INSERT INTO treatments (name, price, drug, type) VALUES ("Pedzinc tabs - Zinc sulphate 20mg B/100", 2000, "Others", "Gut Motility");
INSERT INTO treatments (name, price, drug, type) VALUES ("Annusol oint", 20000, "Antihaemorroids", "Antihaemorroids");
INSERT INTO treatments (name, price, drug, type) VALUES (" Annusol suppositories", 2000, "Antihaemorroids", "Antihaemorroids");
INSERT INTO treatments (name, price, drug, type) VALUES ("Amitriptiline25mg", 200, "Antidepressant", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Chlorpromazine lnj25mg", 7000, "Antidepressant", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Carbamazepine 200mg tabs", 300, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES (" Phenobarbitone 30mg tabs", 100, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES (" Phenobarbitone inj 30mg/ml", 1200, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Diazepam injection IV", 2000, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Diazepam tabs", 100, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES (" Prigabaline 75mg 305", 2000, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("PrigabalinelSOmg 305", 3500, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Desloratidine Smg tabs", 1300, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Cetirizine lOmg tabs", 100, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Cetirizine syrup", 3000, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Loratadine", 250, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Promethazine tabs", 100, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Promethazine syr", 4000, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Chlorpheniramine tabs 4mg", 50, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Chlorpheniramine syr l00ml", 2500, "Anticonvulsants", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Hydrocortsone inj l00mg", 2500, "Steroids", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Dexamethasone inj Bmg", 3500, "Steroids", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Triamcinolone Injection", 5000, "Steroids", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Predinisolone", 100, "Steroids", "CNS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Dextrose 5% 500mls", 3000, "infusions", "INFUSIONS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Dextrose 10% 500mls", 5000, "infusions", "INFUSIONS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Dextrose 50%", 5000, "infusions", "INFUSIONS");
INSERT INTO treatments (name, price, drug, type) VALUES ("DNS 500mls", 3000, "infusions", "INFUSIONS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ringer lactate 500mls", 3000, "", "INFUSIONS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Normal saline 500ml", 3000, "", "INFUSIONS");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ascorbic acid tbs 100mg", 120, "Vitamins/Minerals", "Vitamins/Minerals");
INSERT INTO treatments (name, price, drug, type) VALUES ("Calcium+ Vit.D tabs - MILICAL", 500, "Vitamins/Minerals", "Vitamins/Minerals");
INSERT INTO treatments (name, price, drug, type) VALUES ("VitBl 62 66 612 and folic acid tabs - Nat", 900, "Vitamins/Minerals", "Vitamins/Minerals");
INSERT INTO treatments (name, price, drug, type) VALUES ("Vitamin+minerals- vitacap zincovits", 9000, "Vitamins/Minerals", "Vitamins/Minerals");
INSERT INTO treatments (name, price, drug, type) VALUES ("B complex syrup", 2500, "Vitamins/Minerals", "Vitamins/Minerals");
INSERT INTO treatments (name, price, drug, type) VALUES ("Folic Acid 5mg", 70, "Vitamins/Minerals", "Vitamins/Minerals");
INSERT INTO treatments (name, price, drug, type) VALUES ("Neuroton Tabs", 900, "Vitamins/Minerals", "Vitamins/Minerals");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ferrous sulphate+ folic acids caps", 5000, "Hematenics", "Vitamins/Minerals");
INSERT INTO treatments (name, price, drug, type) VALUES ("Mumfer syrp", 5000, "Hematenics", "Vitamins/Minerals");
INSERT INTO treatments (name, price, drug, type) VALUES ("Mumfer tabs", 3000, "Hematenics", "Vitamins/Minerals");
INSERT INTO treatments (name, price, drug, type) VALUES ("Hemovit syp", 5000, "Hematenics", "Vitamins/Minerals");
INSERT INTO treatments (name, price, drug, type) VALUES ("Globin-z", 4500, "Hematenics", "Vitamins/Minerals");
INSERT INTO treatments (name, price, drug, type) VALUES ("Boric acid ear drop", 2500, "Eye and Ear", "Eye and Ear");
INSERT INTO treatments (name, price, drug, type) VALUES ("Dexamethasone + Gentamycin eye drop", 2000, "Eye and Ear", "Eye and Ear");
INSERT INTO treatments (name, price, drug, type) VALUES ("Candibiotics ear drop", 9000, "Eye and Ear", "Eye and Ear");
INSERT INTO treatments (name, price, drug, type) VALUES ("Chloramphenical eye ointment", 2000, "Eye and Ear", "Eye and Ear");
INSERT INTO treatments (name, price, drug, type) VALUES ("Dexamethasone + Neomycin Eye Drops", 3000, "Eye and Ear", "Eye and Ear");
INSERT INTO treatments (name, price, drug, type) VALUES ("Gentamycin Eye Drops", 2500, "Eye and Ear", "Eye and Ear");
INSERT INTO treatments (name, price, drug, type) VALUES ("Hydrogen peroxide", 2000, "Eye and Ear", "Eye and Ear");
INSERT INTO treatments (name, price, drug, type) VALUES ("Hydrogenperoxide m/w", 2000, "Mouthwash", "Mouthwash");
INSERT INTO treatments (name, price, drug, type) VALUES ("PotasiumPermanganet m/w", 2000, "Mouthwash", "Mouthwash");
INSERT INTO treatments (name, price, drug, type) VALUES ("Listerinm/w", 16000, "Mouthwash", "Mouthwash");
INSERT INTO treatments (name, price, drug, type) VALUES ("Med oral m/w", 4500, "Mouthwash", "Mouthwash");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ephedrine nasal DropsPaedriatic", 3000, "Nasal Prep", "Nasal Prep");
INSERT INTO treatments (name, price, drug, type) VALUES ("Ephedrine nasal Drops adult", 4000, "Nasal Prep", "Nasal Prep");
INSERT INTO treatments (name, price, drug, type) VALUES ("NS Nasal drop", 4000, "Nasal Prep", "Nasal Prep");
INSERT INTO treatments (name, price, drug, type) VALUES ("Sildenafil tabs 50mg", 3000, "ED", "ED");
INSERT INTO treatments (name, price, drug, type) VALUES ("Sildenafil tabs l00mg", 5000, "ED", "ED");
INSERT INTO treatments (name, price, drug, type) VALUES (" Bromocriptine tabs 2.5mg", 700, "Hormonal", "Hormonal Modulation");
INSERT INTO treatments (name, price, drug, type) VALUES ("Dydrogesterone l0mg tabs {duphaston", 2500, "Hormonal", "Hormonal Modulation");
INSERT INTO treatments (name, price, drug, type) VALUES ("Norithisterone 5mg tabs - primolut N", 1500, "Hormonal", "Hormonal Modulation");
INSERT INTO treatments (name, price, drug, type) VALUES ("Clomiphene Tabs 50mg", 1500, "Hormonal", "Hormonal Modulation");